[package]
name = "notes"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.28"
chrono = "0.4.42"
dirs = "6.0.0"
eframe = "0.28"
rand = "0.9.2"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
