[package]
name = "notes"
version = "0.3.1"
edition = "2024"

[dependencies]
egui = "0.32.3"
chrono = "0.4.42"
dirs = "6.0.0"
eframe = "0.32.3"
rand = "0.9.2"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
